### ISSUE TITLE
Policy required is way too much

### ISSUE THREAD

**Issue by agregory999** [oracle-devrel/terraform-oci-arch-devops-cicd-with-functions#9]
In devops-policies, the last one is allowing the DG to manage akll-resources in tenancy.  We should scope this to a compartment, namely the compartment where everything goes.  No shared tenancy admin would ever allow this as is.  There should be an option and docs to create a more restrictive policy.

**Comment by RahulMR42** [comment]
@agregory999 Thanks for the issues.
The polices and its possible unit level controls are updated here - https://docs.oracle.com/en-us/iaas/Content/devops/using/devops_iampolicies.htm
